### ISSUE TITLE
Does not install in sketch 62

### ISSUE THREAD

**Issue by highvoltaged** [charliecm/sketch-snap#1]
Does not install in sketch 62 with runner

**Comment by charliecm** [comment]
@highvoltaged Thanks for raising the issue, I'll look into it. In the meantime, please download the plugin directly from the repo.

**Comment by charliecm** [comment]
Installation through Runner should work now. For future plugin developers, check in your `.sketchplugin` bundle to your repo's root to [ensure Runner can always unpack it](https://twitter.com/abynim/status/1223231776417402881).
