### ISSUE TITLE
This is not an issue! Just the feature request :)  

### ISSUE THREAD

**Issue by ovodesign82** [charliecm/sketch-snap#3]
Hi Charley 

thank you a lot for this awesome plugin 

could you possibly create the one feature for the alignment or snapping 
it would be really great and handy when 
a designer could delete any space (vertical/horizontal) between two layers 
the first selected layer will be a master and the second selected layer will be the layer that should be moved to the master

thank you in advance 
with best regards to you and your work 

Vitaliy Olenyak 
Sr UX Designer

**Comment by charliecm** [comment]
Hi Vitaliy. You can go to `Plugins` → `Snap` → `Snap Settings…` and choose `Group` under “Snap and select layers in…”. Then, group the two layers you want to remove the space between, and run the snap command while selecting your master layer. Let me know if this achieves what you want.
